# Generated by Django 4.0.5 on 2022-08-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('trek_name', models.CharField(max_length=100, verbose_name='Имя трека')),
                ('original_format', models.CharField(max_length=100, verbose_name='Формат оригинала')),
                ('original_track', models.CharField(max_length=100, verbose_name='Оригинальный трек')),
                ('convertable_track', models.CharField(max_length=100, verbose_name='Сконвертированный трек')),
                ('convertable_format', models.CharField(max_length=100, verbose_name='Формат сконвертированного трека')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата конвертации')),
            ],
            options={
                'verbose_name': 'Трек пользователя',
                'verbose_name_plural': 'Треки пользователя',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
