# Generated by Django 4.0.5 on 2022-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('audio_name', models.CharField(max_length=100, verbose_name='Имя трека')),
                ('original_format', models.CharField(max_length=100, verbose_name='Формат оригинала')),
                ('original_path', models.CharField(max_length=100, verbose_name='Оригинальный трек')),
                ('convert_path', models.CharField(max_length=100, verbose_name='Сконвертированный трек')),
                ('convert_format', models.CharField(max_length=100, verbose_name='Формат сконвертированного трека')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата конвертации')),
                ('original_audio_size_b', models.IntegerField(verbose_name='Оригинальный трек. B')),
                ('original_audio_size_mb', models.FloatField(verbose_name='Оригинальный трек. Mb')),
                ('convert_audio_size_b', models.IntegerField(verbose_name='Сконвертированный трек. b')),
                ('convert_audio_size_mb', models.FloatField(verbose_name='Сконвертированный трек Mb')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Трек пользователя',
                'verbose_name_plural': 'Треки пользователя',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
